[project]
name = "detection-server-selab"
version = "0.1.0"
description = "Detection server of SELab for the HyukShinDoYak R&D project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "kafka-python>=2.0.2",
    "pyyaml>=6.0.2",
]
